# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 4 * * 5" # catch SNAPSHOT breaking changes
  workflow_dispatch:

jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Lyo Client samples
        run: |
          mvn -B clean verify --file lyo-client-samples/pom.xml

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build OAuth Discovery application
        run: |
          mvn -B clean verify --file oauth-discovery-dui/pom.xml
      - name: Build OAuth Two-legged samples
        run: |
          mvn -B clean verify --file oauth-twolegged-sample/oauth.sample/pom.xml
          mvn -B clean verify --file oauth-twolegged-sample/oauth-cli-helper/pom.xml
      - name: Build unmaintained samples
        continue-on-error: true
        run: |
          mvn -B clean verify --file xUnmaintained/lyo-2.1/trs4j-bugzilla-sample/pom.xml
          mvn -B clean verify --file xUnmaintained/lyo-2.2/oslc4j-bugzilla-sample/pom.xml
          mvn -B clean verify --file xUnmaintained/lyo-2.3/oslc4j-test/pom.xml
          mvn -B clean verify --file xUnmaintained/lyo-2.4/oslc4j-stockquote/pom.xml
          mvn -B clean verify --file xUnmaintained/lyo-4.1/oslc-java-samples/pom.xml
